//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIRAnnualTaxTable
    {
        public System.Guid Id { get; set; }
        public string Bracket { get; set; }
        public decimal Lo { get; set; }
        public decimal Hi { get; set; }
        public decimal Base { get; set; }
        public decimal percent { get; set; }
    }
}
