//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public System.Guid Id { get; set; }
        public string ext_id { get; set; }
        public string Branch1 { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
