//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeClass
    {
        public EmployeeClass()
        {
            this.ProcessSetups = new HashSet<ProcessSetup>();
            this.PayRates = new HashSet<PayRate>();
            this.PostedCutOffs = new HashSet<PostedCutOff>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid EmployerId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int PayPeriod { get; set; }
        public int WageScheme { get; set; }
        public int RegularDays { get; set; }
        public int DaysPerYear { get; set; }
        public int HoursPerDay { get; set; }
    
        public virtual Employer Employer { get; set; }
        public virtual ICollection<ProcessSetup> ProcessSetups { get; set; }
        public virtual ICollection<PayRate> PayRates { get; set; }
        public virtual ICollection<PostedCutOff> PostedCutOffs { get; set; }
    }
}
