//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> EmployerId { get; set; }
        public string CardNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public bool IsBoy { get; set; }
        public System.DateTime Bday { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Zipcode { get; set; }
        public string PhoneNo { get; set; }
        public string SecurityNo { get; set; }
        public string TIN { get; set; }
        public string HDMF { get; set; }
        public string PhilHealth { get; set; }
        public System.DateTime DateHired { get; set; }
        public Nullable<System.DateTime> DateProbationary { get; set; }
        public Nullable<System.DateTime> DateRegularized { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public string BankAccount { get; set; }
        public Nullable<System.Guid> BankId { get; set; }
        public bool IsProcess { get; set; }
        public bool Deduct_SS { get; set; }
        public bool Deduct_Tax { get; set; }
        public bool Deduct_HDMF { get; set; }
        public bool Deduct_Phealth { get; set; }
        public Nullable<decimal> HDMF_FixAmount { get; set; }
        public Nullable<System.Guid> ShiftId { get; set; }
        public bool DayOffMonday { get; set; }
        public bool DayOffTues { get; set; }
        public bool DayOffWed { get; set; }
        public bool DayOffThurs { get; set; }
        public bool DayOffFri { get; set; }
        public bool DayOffSat { get; set; }
        public bool DayOffSunday { get; set; }
        public bool Paid_LH { get; set; }
        public bool Paid_SH { get; set; }
        public bool IsClocking { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Employee Employees1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual User User { get; set; }
    }
}
