//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public Employer()
        {
            this.ComputationOptions = new HashSet<ComputationOption>();
            this.Deminimis = new HashSet<Deminimi>();
            this.EmployeeClasses = new HashSet<EmployeeClass>();
            this.Employees = new HashSet<Employee>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public string PhoneNo { get; set; }
        public string TIN { get; set; }
        public string SSNo { get; set; }
        public string PhilHealth { get; set; }
        public string RDO { get; set; }
    
        public virtual ICollection<ComputationOption> ComputationOptions { get; set; }
        public virtual ICollection<Deminimi> Deminimis { get; set; }
        public virtual ICollection<EmployeeClass> EmployeeClasses { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
