//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSISTable
    {
        public System.Guid Id { get; set; }
        public string CoverageType { get; set; }
        public decimal PersonalShare_Life { get; set; }
        public decimal PersonalShare_Retirement { get; set; }
        public decimal GovtShare_Life { get; set; }
        public decimal GovtShare_Retirement { get; set; }
    }
}
