//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDMFTable
    {
        public System.Guid Id { get; set; }
        public string Bracket { get; set; }
        public decimal LO { get; set; }
        public decimal HI { get; set; }
        public decimal PercentEmployee { get; set; }
        public decimal PercentEmployer { get; set; }
        public decimal AmountEmployee { get; set; }
        public decimal AmountEmployer { get; set; }
    }
}
