//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanType
    {
        public LoanType()
        {
            this.PayCodes = new HashSet<PayCode>();
        }
    
        public System.Guid Id { get; set; }
        public int Loan { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PayCode> PayCodes { get; set; }
    }
}
