//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayCode
    {
        public PayCode()
        {
            this.PayRates = new HashSet<PayRate>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid EmployerId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string IsTaxable { get; set; }
        public bool IsAttendanceCode { get; set; }
        public bool IsAttendanceEarning { get; set; }
        public string IsEarning { get; set; }
        public System.Guid LoanTypeId { get; set; }
        public System.Guid BIRWTypeId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CurrentComputation CurrentComputation { get; set; }
        public virtual LoanType LoanType { get; set; }
        public virtual ICollection<PayRate> PayRates { get; set; }
    }
}
