//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayrollEntities : DbContext
    {
        public PayrollEntities()
            : base("name=PayrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BIRAnnualTaxTable> BIRAnnualTaxTables { get; set; }
        public virtual DbSet<BIRTaxExemption> BIRTaxExemptions { get; set; }
        public virtual DbSet<BIRWHoldingTaxTable> BIRWHoldingTaxTables { get; set; }
        public virtual DbSet<BIRWType> BIRWTypes { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<ComputationOption> ComputationOptions { get; set; }
        public virtual DbSet<CurrentComputation> CurrentComputations { get; set; }
        public virtual DbSet<Deminimi> Deminimis { get; set; }
        public virtual DbSet<EmployeeClass> EmployeeClasses { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<GSISTable> GSISTables { get; set; }
        public virtual DbSet<HDMFTable> HDMFTables { get; set; }
        public virtual DbSet<LoanType> LoanTypes { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<PayCode> PayCodes { get; set; }
        public virtual DbSet<PayRate> PayRates { get; set; }
        public virtual DbSet<PostedCutOff> PostedCutOffs { get; set; }
        public virtual DbSet<ProcessSetup> ProcessSetups { get; set; }
        public virtual DbSet<SSSBracket> SSSBrackets { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
