//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Employees = new HashSet<Employee>();
            this.PostedCutOffs = new HashSet<PostedCutOff>();
        }
    
        public System.Guid Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<PostedCutOff> PostedCutOffs { get; set; }
    }
}
